Feature/make registration page
divineDuckk/Modsen-Twitter pull request #9
Opened 2024-08-19 13:46 UTC by divineDuckk

2024-08-19 13:53 UTC, ilyaAzarenko requested changes

2024-08-19 13:53 UTC, ilyaAzarenko commented on src/components/DropDown/index.tsx
> +  useEffect(() => {
Бахни отдельный хук

2024-08-19 13:53 UTC, ilyaAzarenko commented on src/components/DropDown/index.tsx
> +          className={isOpen ? styles.dropdownArrowOpen : ''}
подключай cn

2024-08-19 13:53 UTC, ilyaAzarenko commented on src/components/DropDown/index.tsx
> +              onClick={() => handleOptionClick(option)}
карирование

2024-08-19 13:53 UTC, ilyaAzarenko commented on src/utils/functions/getYearsArray.ts
> +    { length: currentYear - 1950 + 1 },
1950 ? а может 1984 ? =D
magic numbers

2024-08-22 15:08 UTC, ilyaAzarenko000 approved these changes

2024-08-22 15:14 UTC, ilyaAzarenko approved these changes

2024-08-22 17:22 UTC, merged